# Generated by Django 3.1.5 on 2021-01-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_backend', '0003_auto_20210115_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='username',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
